name = "x-vite-net"
account_id = "55cb4036f82767a7f0f757a02a1ec8fd"
workers_dev = true
main = "./workers-site/index.js"
compatibility_date = "2024-03-19"

[site]
bucket = "./dist"

[env.production]
zone_id = "28ae64582a3f7d13ee2e46afa8204ef5"

[env.test]
zone_id = "28ae64582a3f7d13ee2e46afa8204ef5"

[env.stage]
zone_id = "28ae64582a3f7d13ee2e46afa8204ef5"
