# This is a basic workflow to help you get started with Actions

name: Deploy To Cloudflare [manual]

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy to: <test|stage|production>'
        required: true
        default: 'test'
      branch:
        description: 'Choose an branch to deploy'
        required: true
        default: 'master' 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: cf-worker

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ubuntu-node-v${{ steps.nvm.outputs.NVMRC }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package.json')) }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          export DESKTOP_WALLET_VERSION=`curl -sL https://api.github.com/repos/vitelabs/vite-wallet/releases/latest | grep '"tag_name":' | cut -d'"' -f4`
          yarn run build:${{ github.event.inputs.environment }}

      - name: Get Build Version
        if: ${{ github.event.inputs.environment == 'production' }}
        id: version
        run: echo "::set-output name=version::$(date +%Y%m%d%H%M)"

      - name: List dist
        run: tree dist

      - name: Log in to Docker Hub
        if: ${{ github.event.inputs.environment == 'production' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        if: ${{ github.event.inputs.environment == 'production' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          tags: vitelabs/vite-web-wallet:${{ steps.version.outputs.version }},vitelabs/vite-web-wallet:latest

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: ${{ github.event.inputs.environment }}

      - uses: Ilshidur/action-slack@2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_AVATAR: repository
        with:
          args: 'Action called, Environment: ${{ github.event.inputs.environment }}, Branch: ${{ github.event.inputs.branch }}, Repository: {{ GITHUB_REPOSITORY }}'
